include $(JPP_DIR)/make/JMakefile

CXXFLAGS  += -I$(H5_CPP_CONVERTER_DIR)/src/

LOADLIBES += $(ROOTLIBS) $(JAANET_LIBS) $(JEVT_LIBS) $(AANET_LIBS) $(JDAQ_LIBS)
LOADLIBES += -lhdf5 -lhdf5_cpp -lz -lm -lpthread

